# Generated by Django 2.2.6 on 2019-11-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventId', models.IntegerField()),
                ('eventName', models.CharField(max_length=250)),
                ('creatorId', models.IntegerField()),
                ('creatorName', models.CharField(max_length=250)),
                ('date', models.IntegerField()),
                ('location', models.CharField(max_length=250)),
                ('numOfParticipants', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('userName', models.CharField(max_length=250)),
                ('numOfCreatedEvents', models.IntegerField()),
                ('numOfParticipatingEvents', models.IntegerField()),
            ],
        ),
    ]
