# Generated by Django 2.2.6 on 2019-11-04 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eventId',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userId',
        ),
    ]
