# Generated by Django 2.2.6 on 2019-11-04 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20191104_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='creatorId',
        ),
        migrations.AlterField(
            model_name='event',
            name='creatorName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.User'),
        ),
    ]
