# Generated by Django 2.2.6 on 2019-11-04 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20191104_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='creatorName',
            new_name='user',
        ),
    ]
