# Generated by Django 2.2.6 on 2019-11-04 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20191104_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='numOfParticipants',
            new_name='participant',
        ),
    ]
